### ISSUE TITLE
Please update for go-smtp v0.10.0+

### ISSUE THREAD

**Issue by mback2k** [emersion/go-smtp-proxy#1]
I am very grateful for this little package, because it enabled me to create https://github.com/mback2k/smtp-dkim-signer. Are there any chances this will be updated for newer go-smtp releases with the breaking changes regarding the switch from a User object to a Session object? I could of course fork it for my own purposes, but would like to stick near the upstream changes. Would you be interested in a PR that updates this package?

**Comment by emersion** [comment]
>Would you be interested in a PR that updates this package?

Yes, definitely!

**Comment by mback2k** [comment]
@emersion I just created a PR with my first try. Would you mind taking a look?
