### ISSUE TITLE
Persistent or keepalive connections to SMTP backends

### ISSUE THREAD

**Issue by kayrus** [emersion/go-smtp-proxy#9]
Is it possible to reuse an established SMTP connection for multiple independent auth sessions?

My SMTP backend server allows limited connections per one IP and I'm looking for a solution to reuse TCP connection for multiple independent sessions.

**Comment by emersion** [comment]
I'm not aware of any way to do this. RFC 4954 states that once an `AUTH` command has been issued, no more `AUTH` commands can be sent for the lifetime of the SMTP session.

**Comment by kayrus** [comment]
Thanks for update. I'm closing an issue then.
